package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opAux        = 3
	opClip       = 4
	opCompressor = 5
	opCrush      = 6
	opDbgain     = 7
	opDelay      = 8
	opDistort    = 9
	opEnvelope   = 10
	opFilter     = 11
	opGain       = 12
	opHold       = 13
	opIn         = 14
	opInvgain    = 15
	opLoadnote   = 16
	opLoadval    = 17
	opMul        = 18
	opMulp       = 19
	opNoise      = 20
	opOscillator = 21
	opOut        = 22
	opOutaux     = 23
	opPan        = 24
	opPop        = 25
	opPush       = 26
	opReceive    = 27
	opSend       = 28
	opSpeed      = 29
	opSync       = 30
	opXch        = 31
)

var transformCounts = [...]int{0, 0, 1, 0, 5, 1, 1, 4, 1, 5, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 1, 0, 0, 0}
