package vm

// Code generated by go generate; DO NOT EDIT.
const (
	opAdd        = 1
	opAddp       = 2
	opAux        = 3
	opClip       = 4
	opCompressor = 5
	opCrush      = 6
	opDbgain     = 7
	opDelay      = 8
	opDistort    = 9
	opEnvelope   = 10
	opEnvelopexp = 11
	opFilter     = 12
	opGain       = 13
	opHold       = 14
	opIn         = 15
	opInvgain    = 16
	opLoadnote   = 17
	opLoadval    = 18
	opMul        = 19
	opMulp       = 20
	opNoise      = 21
	opOscillator = 22
	opOut        = 23
	opOutaux     = 24
	opPan        = 25
	opPop        = 26
	opPush       = 27
	opReceive    = 28
	opSend       = 29
	opSpeed      = 30
	opSync       = 31
	opXch        = 32
)

var transformCounts = [...]int{0, 0, 1, 0, 5, 1, 1, 4, 1, 5, 7, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 1, 0, 0, 0}
