// Code generated by go generate; DO NOT EDIT.
package vm

const (
	opAdd        = 1
	opAddp       = 2
	opAux        = 3
	opClip       = 4
	opCompressor = 5
	opCrush      = 6
	opDelay      = 7
	opDistort    = 8
	opEnvelope   = 9
	opFilter     = 10
	opGain       = 11
	opHold       = 12
	opIn         = 13
	opInvgain    = 14
	opLoadnote   = 15
	opLoadval    = 16
	opMul        = 17
	opMulp       = 18
	opNoise      = 19
	opOscillator = 20
	opOut        = 21
	opOutaux     = 22
	opPan        = 23
	opPop        = 24
	opPush       = 25
	opReceive    = 26
	opSend       = 27
	opSpeed      = 28
	opXch        = 29
)

var transformCounts = [...]int{0, 0, 1, 0, 5, 1, 4, 1, 5, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 6, 1, 2, 1, 0, 0, 0, 1, 0, 0}
