%define BPM 100

%include "sointu/header.inc"

BEGIN_PATTERNS
    PATTERN 64,HLD,HLD,HLD,HLD,HLD,HLD,HLD,0,0,0,0,0,0,0,0
END_PATTERNS

BEGIN_TRACKS
    TRACK VOICES(1),0
END_TRACKS

BEGIN_PATCH
    BEGIN_INSTRUMENT VOICES(1)
        SU_LOADVAL STEREO(0),VALUE(0)
        SU_AUX     STEREO(0),GAIN(64),CHANNEL(1)
        SU_LOADVAL STEREO(0),VALUE(96)
        SU_AUX     STEREO(0),GAIN(128),CHANNEL(0)
    END_INSTRUMENT
END_PATCH

%include "sointu/footer.inc"
