%define BPM 100
%define USE_SECTIONS

%include "../src/sointu.inc"

SU_BEGIN_PATTERNS
    PATTERN 64, HLD, HLD, HLD, HLD, HLD, HLD, HLD,  0, 0, 0, 0, 0, 0, 0, 0
SU_END_PATTERNS

SU_BEGIN_TRACKS
    TRACK VOICES(1),0
SU_END_TRACKS

SU_BEGIN_PATCH
    SU_BEGIN_INSTRUMENT VOICES(1) ; Instrument0
        SU_LOAD_VAL MONO,VALUE(96)
        SU_SEND     MONO,AMOUNT(96),GLOBALPORT(1,3,load_val,value) + SEND_POP
        SU_LOAD_VAL MONO,VALUE(64)
        SU_LOAD_VAL MONO,VALUE(64)
        SU_OUT      STEREO,GAIN(128)
    SU_END_INSTRUMENT
    SU_BEGIN_INSTRUMENT VOICES(1)  ; Instrument1
        SU_LOAD_VAL MONO,VALUE(32)
        SU_SEND     MONO,AMOUNT(96),GLOBALPORT(0,2,load_val,value) + SEND_POP
        SU_LOAD_VAL MONO,VALUE(64)
        SU_LOAD_VAL MONO,VALUE(64)
        SU_OUT      STEREO,GAIN(128)
    SU_END_INSTRUMENT
SU_END_PATCH

%include "../src/sointu.asm"
