%define BPM 100

%include "sointu/header.inc"

BEGIN_PATTERNS
    PATTERN 64, HLD, HLD, HLD, HLD, HLD, HLD, HLD,HLD, HLD, HLD, 0, 0, 0, 0, 0
END_PATTERNS

BEGIN_TRACKS
    TRACK VOICES(1),0
END_TRACKS

BEGIN_PATCH
    BEGIN_INSTRUMENT VOICES(1) ; Instrument0
        SU_ENVELOPE MONO,ATTACK(80),DECAY(80),SUSTAIN(64),RELEASE(80),GAIN(128)
        SU_ENVELOPE MONO,ATTACK(80),DECAY(80),SUSTAIN(64),RELEASE(80),GAIN(128)
        SU_OSCILLATOR MONO,TRANSPOSE(120),DETUNE(64),PHASE(0),COLOR(128),SHAPE(96),GAIN(128),TYPE(SINE),LFO(1),UNISON(0)
        SU_SEND MONO,AMOUNT(68),VOICE(0),UNIT(0),PORT(0),SENDPOP(0)
        SU_SEND MONO,AMOUNT(68),VOICE(0),UNIT(0),PORT(1),SENDPOP(0)
        ; Sustain modulation seems not to be implemented
        SU_SEND MONO,AMOUNT(68),VOICE(0),UNIT(0),PORT(3),SENDPOP(0)
        SU_SEND MONO,AMOUNT(68),VOICE(0),UNIT(1),PORT(4),SENDPOP(1)
        SU_OUT  STEREO,GAIN(110)
    END_INSTRUMENT
END_PATCH

%include "sointu/footer.inc"
