%define BPM 100
%define INCLUDE_DELAY_MODULATION

%include "sointu/header.inc"

BEGIN_PATTERNS
    PATTERN 80, HLD, HLD, HLD, HLD, HLD, HLD, HLD, HLD, HLD, HLD, 0, 0, 0, 0, 0
END_PATTERNS

BEGIN_TRACKS
    TRACK VOICES(1),0
END_TRACKS

BEGIN_PATCH
    BEGIN_INSTRUMENT VOICES(1) ; Instrument0
        SU_ENVELOPE MONO,ATTAC(80),DECAY(80),SUSTAIN(64),RELEASE(80),GAIN(128)
        SU_OSCILLAT MONO,TRANSPOSE(64),DETUNE(64),PHASE(0),COLOR(128),SHAPE(64),GAIN(128),FLAGS(TRISAW)
        SU_MULP     MONO
        SU_DELAY    MONO,PREGAIN(40),DRY(128),FEEDBACK(0),DAMP(64),DELAY(0),COUNT(1)
        SU_PAN      MONO,PANNING(64)
        SU_OUT      STEREO,GAIN(128)
        SU_OSCILLAT MONO,TRANSPOSE(50),DETUNE(64),PHASE(64),COLOR(128),SHAPE(64),GAIN(128),FLAGS(SINE+LFO)
        SU_SEND     MONO,AMOUNT(65),UNIT(3),PORT(5),FLAGS(SEND_POP)
    END_INSTRUMENT
END_PATCH

BEGIN_DELTIMES
    DELTIME 1000
END_DELTIMES

%include "sointu/footer.inc"
