%define BPM 100

%include "sointu/header.inc"

BEGIN_PATTERNS
    PATTERN 64,HLD,HLD,HLD,HLD,HLD,HLD,HLD, 0,  0,  0,0,0,0,0,0
    PATTERN  0,  0,  0,  0,  0,  0,  0,  0,64,HLD,HLD,0,0,0,0,0
END_PATTERNS

BEGIN_TRACKS
    TRACK VOICES(1),0
    TRACK VOICES(1),1
END_TRACKS

BEGIN_PATCH
    BEGIN_INSTRUMENT VOICES(1) ; Instrument0
        SU_ENVELOPE MONO,ATTACK(64),DECAY(64),SUSTAIN(64),RELEASE(80),GAIN(128)
        SU_ENVELOPE MONO,ATTACK(64),DECAY(64),SUSTAIN(64),RELEASE(80),GAIN(0)
        SU_OUT      STEREO,GAIN(128)
    END_INSTRUMENT
    BEGIN_INSTRUMENT VOICES(1) ; Instrument1
        SU_ENVELOPE MONO,ATTACK(32),DECAY(32),SUSTAIN(64),RELEASE(80),GAIN(0)
        SU_ENVELOPE MONO,ATTACK(32),DECAY(32),SUSTAIN(64),RELEASE(80),GAIN(128)
        SU_OUT      STEREO,GAIN(128)
    END_INSTRUMENT
END_PATCH

%include "sointu/footer.inc"
