%include "sointu/header.inc"

BEGIN_SONG BPM(100),OUTPUT_16BIT(0),CLIP_OUTPUT(0),DELAY_MODULATION(0)

BEGIN_PATTERNS
    PATTERN 64,HLD,HLD,HLD,HLD,HLD,HLD,HLD,0,0,0,0,0,0,0,0
END_PATTERNS

BEGIN_TRACKS
    TRACK VOICES(1),0
END_TRACKS

BEGIN_PATCH
    BEGIN_INSTRUMENT VOICES(1)
        SU_LOADVAL STEREO(0),VALUE(96)
        SU_SEND    STEREO(0),AMOUNT(96),VOICE(2),UNIT(3),PORT(0),SENDPOP(1)
        SU_LOADVAL STEREO(0),VALUE(64)
        SU_LOADVAL STEREO(0),VALUE(64)
        SU_OUT     STEREO(1),GAIN(128)
    END_INSTRUMENT
    BEGIN_INSTRUMENT VOICES(1)
        SU_LOADVAL STEREO(0),VALUE(32)
        SU_SEND    STEREO(0),AMOUNT(96),VOICE(1),UNIT(2),PORT(0),SENDPOP(1)
        SU_LOADVAL STEREO(0),VALUE(64)
        SU_LOADVAL STEREO(0),VALUE(64)
        SU_OUT     STEREO(1),GAIN(128)
    END_INSTRUMENT
END_PATCH

END_SONG
